Fix exception in logging of failed container_run cmd
ValueError: cannot switch from manual field
            specification to automatic field numbering

Signed-off-by: Adam Stokes <adam.stokes@ubuntu.com>